/*
 * Replays the projection conformance vectors (../../vectors/ontos-projection.json) and
 * pins byte preservation against the frozen codec vectors (../../../../vectors/codec.json).
 *
 * The vectors are the SHARED LOCK: one file, replayed by every face (rs, go, and this
 * one). They are HAND-AUTHORED from PROJECTION.md and were NOT generated by an
 * implementation (the file's own `note` says so), so a disagreement between this face
 * and a golden is this face's bug, an error in the golden, or an ambiguity in
 * PROJECTION.md — ruled on by the ontos maintainers, never resolved by editing until it passes.
 *
 * Mirrors projection/deixis/go/vectors_test.go and projection/deixis/rs/tests/vectors.rs
 * section-for-section, deliberately: the three faces are peers, so their suites should
 * fail on the same inputs.
 */

import test from "node:test";
import assert from "node:assert/strict";
import { readFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";

import { Node, some } from "@bitspark/deixis-core";
import { PROFILE as POS_PROFILE, key } from "@bitspark/deixis-pos";
import { atom, tuple, equals, type Value } from "@bitspark/ontos-core";
import { decode, encode } from "@bitspark/ontos-codec";

import {
  type BytesNode,
  type Payload,
  POSITION_SPELLING,
  PROFILE,
  Unrecognized,
  nodeEq,
  project,
  recognize,
} from "../src/index.ts";

const here = dirname(fileURLToPath(import.meta.url));
// projection/deixis/ts/test -> projection/deixis/vectors is two levels up …
const projectionVectors = join(here, "..", "..", "vectors", "ontos-projection.json");
// … and the repo-root vectors/ is four.
const codecVectors = join(here, "..", "..", "..", "..", "vectors", "codec.json");

function hexToBytes(hex: string): Uint8Array {
  if (hex.length % 2 !== 0) throw new Error(`odd-length hex: ${hex}`);
  const out = new Uint8Array(hex.length / 2);
  for (let i = 0; i < out.length; i += 1) {
    out[i] = Number.parseInt(hex.slice(i * 2, i * 2 + 2), 16);
  }
  return out;
}

function bytesToHex(bytes: Uint8Array): string {
  return Array.from(bytes, (b) => b.toString(16).padStart(2, "0")).join("");
}

/** The family's ontos notation: {"atom": hex} | {"tuple": [...]}. */
function valueOf(j: any): Value {
  if (typeof j.atom === "string") return atom(hexToBytes(j.atom));
  if (Array.isArray(j.tuple)) return tuple(j.tuple.map(valueOf));
  throw new Error(`value must be {atom} or {tuple}: ${JSON.stringify(j)}`);
}

/**
 * The parallel deixis notation, mandatory-value model:
 * {"own": hex | null, "children": [[hexKey, node], …]} with children in AUTHORED order.
 *
 * `own` is the whole payload: a hex string is Some(bytes) — including "" for Some(empty)
 * — and null is None. Every node carries both halves, so there is no constructor to pick.
 */
function nodeOf(j: any): BytesNode {
  assert.ok(
    j !== null && typeof j === "object" && "own" in j && Array.isArray(j.children),
    `node must be {own, children}: ${JSON.stringify(j)}`,
  );
  const own: Payload = j.own === null ? undefined : some(hexToBytes(j.own));
  return Node.compose<Payload>(
    own,
    j.children.map((pair: any) => {
      assert.ok(
        Array.isArray(pair) && pair.length === 2,
        `child is not a [key, node] pair: ${JSON.stringify(pair)}`,
      );
      return [hexToBytes(pair[0]), nodeOf(pair[1])] as const;
    }),
  );
}


function load(): any {
  const doc = JSON.parse(readFileSync(projectionVectors, "utf8"));
  // CONTROL: a zero-case run must fail loudly rather than pass vacuously.
  assert.ok(doc.project.length >= 10, "vector file shrank? (project)");
  assert.ok(doc.unrecognized.length >= 7, "vector file shrank? (unrecognized)");
  assert.ok(doc.value_pairs.length >= 6, "vector file shrank? (value_pairs)");
  assert.ok(doc.d_equal_nodes.length >= 1, "vector file shrank? (d_equal_nodes)");
  assert.ok(doc.paths.length >= 6, "vector file shrank? (paths)");
  return doc;
}

test("profile and position spelling match the vectors and the deixis-pos dependency", () => {
  const doc = load();
  assert.equal(doc.profile, PROFILE);
  assert.equal(doc.position_spelling, POSITION_SPELLING);
  // The spelling this face names is the one the dependency actually implements.
  assert.equal(POS_PROFILE, POSITION_SPELLING);
});

// P is pinned forwards, and — read backwards — so are laws 1 and 3.
test("project cases pin P and R (laws 1-3)", () => {
  const doc = load();
  for (const c of doc.project) {
    const value = valueOf(c.value);
    const want = nodeOf(c.node);

    // P(value) = node, under deixis identity (authored entry order must not matter).
    assert.ok(nodeEq(project(value), want), `P mismatch: ${c.name}`);

    // Law 1: R(P(v)) = v — projection loses nothing.
    assert.ok(equals(recognize(project(value)), value), `law 1: R(P(v)) ≠ v: ${c.name}`);

    // Law 3: R(d) = v implies P(v) =D d — recognition inverts onto the SAME node.
    const from = recognize(want);
    assert.ok(equals(from, value), `R(node) ≠ value: ${c.name}`);
    assert.ok(nodeEq(project(from), want), `law 3: P(R(d)) is not =D d: ${c.name}`);
  }
});

// Law 6: Node(Some(""), {}) ≠D Node(None, {}) — the case a lax bridge merges first.
// In the mandatory-value model BOTH are childless, so the whole distinction rests on the
// payload: a face comparing only "is there a value at all" would merge them.
test("empty atom and empty tuple stay distinct (law 6)", () => {
  const leaf = project(atom());
  const empty = project(tuple());
  assert.notEqual(leaf.own(), undefined, "P(Atom(\"\")) must carry Some(\"\")");
  assert.equal(empty.own(), undefined, "P(Tuple()) must carry None");
  assert.equal(leaf.length, 0);
  assert.equal(empty.length, 0);
  assert.ok(!nodeEq(leaf, empty), "law 6: P(Atom(\"\")) and P(Tuple()) collapsed to the same node");
  assert.ok(!equals(recognize(leaf), recognize(empty)), "law 6: they recognized back to the same value");
});

// Refusal is the half a single implementation cannot witness on its own: the REASON
// space is the under-determined surface of this profile.
test("unrecognized cases pin refusal — the outcome, never the wording", (t) => {
  const doc = load();
  for (const c of doc.unrecognized) {
    const node = nodeOf(c.node);
    let refused: unknown;
    try {
      const got = recognize(node);
      assert.fail(`R ACCEPTED a node the profile says must be refused (${c.name}) — returned ${got.toString()}`);
    } catch (e) {
      if (e instanceof assert.AssertionError) throw e;
      refused = e;
    }
    // The OUTCOME (refusal) is the hard requirement, and it must be the TYPED refusal —
    // any other throw would be a crash, not a recognizer verdict.
    assert.ok(refused instanceof Unrecognized, `${c.name}: refused with something other than Unrecognized: ${String(refused)}`);
    // The KIND is normative and IS auto-matched: a node refused for its SHAPE must not
    // be reported as a key problem, or the explanation names a culprit that is fine.
    assert.equal(
      refused.kind,
      c.kind,
      `${c.name}: refused for the wrong reason — golden kind ${c.kind}, ours ${refused.kind} (${refused.message})`,
    );
    // The REASON is reported, never auto-matched: the golden text is informative
    // (PROJECTION.md §Vectors), and adjusting code until the strings agree would be
    // matching a diagnostic the laws never mention.
    if (refused.message !== c.reason) {
      t.diagnostic(`REASON DIVERGENCE (not a failure) ${c.name}\n  golden: ${c.reason}\n  ours:   ${refused.message}`);
    }
  }
});

// Law 4: P(v) =D P(w) iff v =O w. An `iff`, so the corpus must carry BOTH directions —
// a section of only-distinct pairs tests half a law and reads as testing all of it.
test("value pairs pin law 4 in both directions", () => {
  const doc = load();
  let sawEqual = false;
  let sawDistinct = false;
  for (const c of doc.value_pairs) {
    const left = valueOf(c.left);
    const right = valueOf(c.right);
    if (c.equal) sawEqual = true;
    else sawDistinct = true;
    assert.equal(equals(left, right), c.equal, `the corpus claim about =O is wrong: ${c.name}`);
    assert.equal(nodeEq(project(left), project(right)), c.equal, `law 4: ${c.name}`);
  }
  assert.ok(sawEqual && sawDistinct, "value_pairs must carry equal AND distinct cases, or it pins only half of law 4");
});

// Equality is over the WHOLE Option payload. These pairs must stay apart, and each names
// a way a lax relation would merge them: None vs Some(""), and two Somes differing only
// in length.
test("d-distinct nodes pin payload equality", () => {
  const doc = load();
  assert.ok(doc.d_distinct_nodes.length > 0, "d_distinct_nodes section is empty — vector file shrank?");
  for (const c of doc.d_distinct_nodes) {
    const left = nodeOf(c.left);
    const right = nodeOf(c.right);
    assert.ok(!nodeEq(left, right), `=D merged two distinct nodes (${c.name}): ${c.reason}`);
    // Reflexivity, so a relation that merely answers false cannot pass this.
    assert.ok(nodeEq(left, left) && nodeEq(right, right), `${c.name}: =D is not reflexive`);
  }
});

// Law 5: d =D e implies the same recognizer outcome, and equal outputs on success.
// Needs two NODES; no single-value case can carry it.
test("d-equal nodes pin law 5", () => {
  const doc = load();
  for (const c of doc.d_equal_nodes) {
    const left = nodeOf(c.left);
    const right = nodeOf(c.right);
    assert.ok(nodeEq(left, right), `the corpus claim about =D is wrong: ${c.name}`);
    const a = outcome(left);
    const b = outcome(right);
    assert.equal(a.ok, b.ok, `law 5: equal nodes reached different outcomes: ${c.name}`);
    if (a.ok && b.ok) assert.ok(equals(a.value, b.value), `law 5: equal nodes recognized to different values: ${c.name}`);
  }
});

function outcome(node: BytesNode): { ok: true; value: Value } | { ok: false; error: Unrecognized } {
  try {
    return { ok: true, value: recognize(node) };
  } catch (e) {
    if (e instanceof Unrecognized) return { ok: false, error: e };
    throw e;
  }
}

/** Follow an ontos index path. `undefined` = the path does not resolve. */
function walkValue(value: Value, path: readonly number[]): Value | undefined {
  let cur: Value | undefined = value;
  for (const i of path) {
    if (cur === undefined || cur.kind !== "tuple") return undefined;
    cur = cur.at(i);
  }
  return cur;
}

/**
 * Follow the corresponding deixis key path (κ(i₀), …, κ(iₖ)) — deixis's own `resolve`,
 * which compares keys octet-wise and never parses one, exactly as R does.
 */
function walkNode(node: BytesNode, path: readonly number[]): BytesNode | undefined {
  return node.at(path.map((i) => key(BigInt(i))));
}

// Law 7: the index path resolves in v IFF the key path resolves in P(v), and on success it
// reaches P of the SAME subvalue. Both halves matter — a face could agree on reachability
// everywhere and still land on the wrong node.
test("paths pin law 7", () => {
  const doc = load();
  let sawResolving = false;
  let sawAbsent = false;
  for (const c of doc.paths) {
    const value = valueOf(c.value);
    const path: number[] = c.index_path;
    if (c.resolves) sawResolving = true;
    else sawAbsent = true;

    const byIndex = walkValue(value, path);
    assert.equal(byIndex !== undefined, c.resolves, `the corpus claim about the INDEX path is wrong: ${c.name}`);

    const byKeys = walkNode(project(value), path);
    assert.equal(byKeys !== undefined, c.resolves, `law 7: the two paths disagree about reachability: ${c.name}`);

    if (c.resolves) {
      const sub = valueOf(c.subvalue);
      assert.ok(equals(byIndex!, sub), `the corpus claim about the SUBVALUE is wrong: ${c.name}`);
      assert.ok(nodeEq(byKeys!, project(sub)), `law 7: the key path reaches a node that is not P(subvalue): ${c.name}`);
    }
  }
  assert.ok(sawResolving && sawAbsent, "paths must carry resolving AND non-resolving cases");
});

// toOntosBytes(P(v)) = encodeOntosV1(v), byte for byte, over the frozen corpus: decode
// each frozen encoding, project, recognize back, re-encode, compare. This is the
// profile's ONE byte-level statement, and it is compositional through R and the frozen
// codec — no deixis codec's bytes are related to ontos-codec-v1, by design.
test("frozen codec bytes survive the round trip through P and R", () => {
  const doc = JSON.parse(readFileSync(codecVectors, "utf8"));
  assert.equal(doc.codec, "ontos-codec-v1");
  assert.ok(doc.encode.length >= 5, "codec vector file shrank?");
  for (const c of doc.encode) {
    const frozen = hexToBytes(c.hex);
    const value = decode(frozen);
    // The authoring notation and the frozen bytes must name the same value, or the
    // corpus is the thing under suspicion.
    assert.ok(equals(value, valueOf(c.value)), `codec corpus self-disagreement: ${c.name}`);

    const roundTripped = recognize(project(value));
    assert.equal(bytesToHex(encode(roundTripped)), c.hex, `codec bytes changed through the bridge: ${c.name}`);
    assert.ok(equals(roundTripped, value), `law 1 over the codec corpus: ${c.name}`);
  }
});
