package projection_test

import (
	"bytes"
	"encoding/hex"
	"encoding/json"
	"errors"
	"os"
	"path/filepath"
	"testing"

	deixis "github.com/bitspark/deixis/core/go"
	pos "github.com/bitspark/deixis/pos/go"
	core "github.com/bitspark/ontos/core/go"
	projection "github.com/bitspark/ontos/projection/deixis/go"
)

// The vectors are the SHARED LOCK: one file, replayed by every face. They are also only
// evidence and not authority. They are HAND-AUTHORED from PROJECTION.md and were NOT
// generated by an implementation (the file's own `note` says so, and §Vectors agrees) —
// so a disagreement between this face and a golden is one of three things: this face's
// bug, an error in the hand-authored golden, or an ambiguity in PROJECTION.md that lets
// two honest readers diverge. Ruled on by the ontos maintainers, never resolved by editing
// until it passes.
//
// (An earlier version of this comment said the goldens were produced by the first
// implementation. That was wrong, and it UNDERSTATED the result: hand-authored vectors
// mean a clean replay is two independent readings of the spec agreeing, not a face
// re-deriving another face's output.)

type vectorFile struct {
	Profile          string             `json:"profile"`
	PositionSpelling string             `json:"position_spelling"`
	Project          []projectCase      `json:"project"`
	Unrecognized     []unrecognizedCase `json:"unrecognized"`
	ValuePairs       []valuePairCase    `json:"value_pairs"`
	DEqualNodes      []dEqualNodeCase   `json:"d_equal_nodes"`
	DDistinctNodes   []dDistinctCase    `json:"d_distinct_nodes"`
	Paths            []pathCase         `json:"paths"`
}

// Law 7 is the last law to reach the corpus (ontos-internal#290). Until it did, a face could
// replay every case in the file and test law 7 ZERO times -- only `rs` exercised the
// commutation, in its own unit test, which is the harness-not-artifact shape ontos-internal#286
// removed from laws 4 and 5.

type pathCase struct {
	Name      string          `json:"name"`
	Value     json.RawMessage `json:"value"`
	IndexPath []int           `json:"index_path"`
	Resolves  bool            `json:"resolves"`
	Subvalue  json.RawMessage `json:"subvalue"`
}

// Laws 4 and 5 are claims about a PAIR, and no single-value case can carry one. Before
// ontos-internal#286 they lived in the Rust harness's own pairwise loop, so a face written from
// PROJECTION.md alone -- this one -- replayed every vector green having never tested
// law 4 at all. The obligation now lives in the corpus, where a witness is handed it.

type valuePairCase struct {
	Name  string          `json:"name"`
	Left  json.RawMessage `json:"left"`
	Right json.RawMessage `json:"right"`
	Equal bool            `json:"equal"`
}

type dEqualNodeCase struct {
	Name  string          `json:"name"`
	Left  json.RawMessage `json:"left"`
	Right json.RawMessage `json:"right"`
}

type projectCase struct {
	Name  string          `json:"name"`
	Value json.RawMessage `json:"value"`
	Node  json.RawMessage `json:"node"`
}

type unrecognizedCase struct {
	Name string          `json:"name"`
	Node json.RawMessage `json:"node"`
	// Kind is NORMATIVE. The mandatory-value model admits shapes the old leaf/struct
	// sum could not express, and a face that reported every one of them as a key
	// problem would be naming a culprit that is fine.
	Kind   string `json:"kind"`
	Reason string `json:"reason"`
}

// dDistinctCase pins that =D separates payloads it must separate: None from Some, and
// two Somes whose bytes differ. It is the complement of dEqualNodeCase.
type dDistinctCase struct {
	Name   string          `json:"name"`
	Left   json.RawMessage `json:"left"`
	Right  json.RawMessage `json:"right"`
	Reason string          `json:"reason"`
}

func load(t *testing.T) vectorFile {
	t.Helper()
	// ⛔ THIS PATH LEAVES THIS MODULE, AND THAT MAKES A BARE `go test` LIE.
	// projection/deixis/go has its own go.mod (separate on purpose — it depends on
	// deixis, and ontos/core must not). Go hashes the files a test opens into its
	// test-cache key ONLY while they are inside that test's own module, so the corpus
	// one level up is INVISIBLE to the cache key: change ONLY the corpus and a bare
	// `go test` replays a cached PASS that never saw it.
	//
	// MEASURED both arms on this repo, module boundary the only variable:
	//   fixture INSIDE the module  (root go.mod; data/json/go -> ../../../vectors/)
	//     falsify -> bare `go test ./...`  FAIL, cache correctly invalidated
	//   fixture OUTSIDE the module (this package)
	//     falsify -> bare `go test`        ** cached PASS **
	// ⇒ NOT "go test ignores data files" — it tracks them, up to the module boundary.
	//
	// SO: RED-PROVE THIS SUITE WITH `-count=1` OR THE PROOF IS VOID. CI passes it
	// (.github/workflows/vectors.yml, the nested-module loop); a local run does not.
	p := filepath.Join("..", "vectors", "ontos-projection.json")
	raw, err := os.ReadFile(p)
	if err != nil {
		t.Fatalf("reading %s: %v", p, err)
	}
	var vf vectorFile
	if err := json.Unmarshal(raw, &vf); err != nil {
		t.Fatalf("parsing %s: %v", p, err)
	}
	// CONTROL: a zero-case run must fail loudly rather than pass vacuously.
	if len(vf.Paths) == 0 {
		t.Fatalf("vector file yielded 0 paths cases — a dead read, not a clean sweep")
	}
	if len(vf.ValuePairs) == 0 || len(vf.DEqualNodes) == 0 {
		t.Fatalf("vector file yielded %d value_pairs / %d d_equal_nodes — a dead read, not a clean sweep",
			len(vf.ValuePairs), len(vf.DEqualNodes))
	}
	if len(vf.Project) == 0 || len(vf.Unrecognized) == 0 {
		t.Fatalf("vector file yielded %d project / %d unrecognized cases — a dead read, not a clean sweep",
			len(vf.Project), len(vf.Unrecognized))
	}
	return vf
}

// parseValue reads the family's ontos notation: {"atom": hex} | {"tuple": [...]}.
func parseValue(t *testing.T, raw json.RawMessage) core.Value {
	t.Helper()
	var probe map[string]json.RawMessage
	if err := json.Unmarshal(raw, &probe); err != nil {
		t.Fatalf("value is not an object: %s", raw)
	}
	if a, ok := probe["atom"]; ok {
		var s string
		if err := json.Unmarshal(a, &s); err != nil {
			t.Fatalf("atom is not a string: %s", a)
		}
		b, err := hex.DecodeString(s)
		if err != nil {
			t.Fatalf("atom %q is not hex: %v", s, err)
		}
		return core.NewAtom(b)
	}
	if tp, ok := probe["tuple"]; ok {
		var items []json.RawMessage
		if err := json.Unmarshal(tp, &items); err != nil {
			t.Fatalf("tuple is not an array: %s", tp)
		}
		vals := make([]core.Value, 0, len(items))
		for _, it := range items {
			vals = append(vals, parseValue(t, it))
		}
		return core.NewTuple(vals...)
	}
	t.Fatalf("value is neither atom nor tuple: %s", raw)
	return nil
}

// parseNode reads the parallel deixis notation, mandatory-value model:
//
//	{"own": hex | null, "children": [[hexKey, node], …]}   entries in AUTHORED order
//
// `own` is the whole payload: a hex string is Some(bytes) — including "" for Some(&[]) —
// and null is None. Every node carries both halves, so there is no constructor to pick.
func parseNode(t *testing.T, raw json.RawMessage) projection.Node {
	t.Helper()
	var probe struct {
		Own      *string             `json:"own"`
		Children [][]json.RawMessage `json:"children"`
	}
	if err := json.Unmarshal(raw, &probe); err != nil {
		t.Fatalf("node is not an object: %s", raw)
	}

	own := deixis.None[[]byte]()
	if probe.Own != nil {
		b, err := hex.DecodeString(*probe.Own)
		if err != nil {
			t.Fatalf("own %q is not hex: %v", *probe.Own, err)
		}
		own = deixis.Some(b)
	}

	entries := make([]deixis.Entry[projection.Payload], 0, len(probe.Children))
	for _, pr := range probe.Children {
		if len(pr) != 2 {
			t.Fatalf("child is not a [key, node] pair: %v", pr)
		}
		var ks string
		if err := json.Unmarshal(pr[0], &ks); err != nil {
			t.Fatalf("child key is not a string: %s", pr[0])
		}
		kb, err := hex.DecodeString(ks)
		if err != nil {
			t.Fatalf("child key %q is not hex: %v", ks, err)
		}
		entries = append(entries, deixis.Entry[projection.Payload]{Key: kb, Node: parseNode(t, pr[1])})
	}

	node, err := deixis.Compose(own, entries)
	if err != nil {
		t.Fatalf("vector node rejected by deixis: %v", err)
	}
	return node
}

// nodesEqual is the face's own exported relation, not a test-local one: the equality
// over the whole Option payload is part of what this face must supply, so the corpus
// must exercise THAT rather than a copy of it written to agree.
func nodesEqual(a, b projection.Node) bool {
	return projection.NodeEq(a, b)
}

func TestProfileAndSpellingMatchTheVectors(t *testing.T) {
	vf := load(t)
	if vf.Profile != projection.Profile {
		t.Errorf("profile: vectors say %q, this face says %q", vf.Profile, projection.Profile)
	}
	if vf.PositionSpelling != projection.PositionSpelling {
		t.Errorf("position_spelling: vectors say %q, this face says %q", vf.PositionSpelling, projection.PositionSpelling)
	}
}

// P is pinned forwards, and — read backwards — so are laws 1 and 3.
func TestProjectVectorsReplay(t *testing.T) {
	vf := load(t)
	for _, c := range vf.Project {
		t.Run(c.Name, func(t *testing.T) {
			value := parseValue(t, c.Value)
			want := parseNode(t, c.Node)

			if got := projection.Project(value); !nodesEqual(got, want) {
				t.Errorf("P mismatch\n  value: %s\n  want:  %v\n  got:   %v", value, want, got)
			}

			// Law 1: R(P(v)) = v — projection loses nothing.
			back, err := projection.Recognize(projection.Project(value))
			if err != nil {
				t.Fatalf("law 1: R(P(v)) refused: %v", err)
			}
			if !core.Equal(back, value) {
				t.Errorf("law 1: R(P(v)) = %s, want %s", back, value)
			}

			// Law 3: R(d) = v implies P(v) =D d — recognition inverts onto the SAME node.
			from, err := projection.Recognize(want)
			if err != nil {
				t.Fatalf("R refused a node the vectors say is in the image of P: %v", err)
			}
			if !core.Equal(from, value) {
				t.Errorf("R(node) = %s, want %s", from, value)
			}
			if !nodesEqual(projection.Project(from), want) {
				t.Errorf("law 3: P(R(d)) is not =D d")
			}
		})
	}
}

// Law 6: Node(Some(""), {}) ≠D Node(None, {}) — the case a lax bridge merges first.
// In the mandatory-value model BOTH are childless, so the whole distinction rests on the
// payload: a face comparing only "is there a value" would merge them.
func TestEmptyAtomAndEmptyTupleStayDistinct(t *testing.T) {
	leaf := projection.Project(core.NewAtom([]byte{}))
	empty := projection.Project(core.NewTuple())
	if _, some := leaf.Own().Get(); !some {
		t.Fatal("P(Atom(\"\")) must carry Some(\"\"), not None")
	}
	if _, some := empty.Own().Get(); some {
		t.Fatal("P(Tuple()) must carry None")
	}
	if leaf.Len() != 0 || empty.Len() != 0 {
		t.Fatal("both empties are childless; the difference is the payload alone")
	}
	if nodesEqual(leaf, empty) {
		t.Fatal("law 6: P(Atom(\"\")) and P(Tuple()) collapsed to the same node")
	}
	a, err := projection.Recognize(leaf)
	if err != nil {
		t.Fatalf("R refused P(Atom(\"\")): %v", err)
	}
	b, err := projection.Recognize(empty)
	if err != nil {
		t.Fatalf("R refused P(Tuple()): %v", err)
	}
	if core.Equal(a, b) {
		t.Fatal("law 6: they recognized back to the same value")
	}
}

// Refusal is the half a single implementation cannot witness on its own: the REASON
// space is the under-determined surface of this profile.
func TestUnrecognizedVectorsReplay(t *testing.T) {
	vf := load(t)
	for _, c := range vf.Unrecognized {
		t.Run(c.Name, func(t *testing.T) {
			node := parseNode(t, c.Node)
			got, err := projection.Recognize(node)
			if err == nil {
				t.Fatalf("R ACCEPTED a node the profile says must be refused — returned %s", got)
			}
			// The KIND is normative and IS auto-matched: a node refused for its shape
			// must not be reported as a key problem. Only the prose stays free.
			var u *projection.Unrecognized
			if !errors.As(err, &u) {
				t.Fatalf("refusal is not a *projection.Unrecognized: %T", err)
			}
			if string(u.Kind) != c.Kind {
				t.Fatalf("refused for the wrong reason: golden kind %q, ours %q (%v)", c.Kind, u.Kind, err)
			}
			// The OUTCOME (refusal) is asserted above and is the hard requirement.
			// The REASON is reported, never auto-matched: if this face's spec-derived
			// wording diverges from the golden, that is a finding for the ontos maintainers —
			// adjusting the code until the strings agree would spend exactly the
			// independence this face was written to provide.
			if err.Error() != c.Reason {
				t.Logf("REASON DIVERGENCE (not a failure — route to the ontos maintainers)\n  golden: %s\n  ours:   %s", c.Reason, err.Error())
			}
		})
	}
}

// Law 4: P(v) =D P(w) iff v =O w. An `iff`, so the corpus must carry BOTH directions --
// a section of only-distinct pairs tests half a law and reads as testing all of it.
func TestValuePairsPinLaw4(t *testing.T) {
	vf := load(t)
	sawEqual, sawDistinct := false, false
	for _, c := range vf.ValuePairs {
		c := c
		t.Run(c.Name, func(t *testing.T) {
			left := parseValue(t, c.Left)
			right := parseValue(t, c.Right)
			if c.Equal {
				sawEqual = true
			} else {
				sawDistinct = true
			}
			if core.Equal(left, right) != c.Equal {
				t.Fatalf("the corpus claim about =O is wrong: want equal=%v", c.Equal)
			}
			if got := nodesEqual(projection.Project(left), projection.Project(right)); got != c.Equal {
				t.Errorf("law 4: P(left) =D P(right) is %v, want %v", got, c.Equal)
			}
		})
	}
	if !sawEqual || !sawDistinct {
		t.Fatal("value_pairs must carry equal AND distinct cases, or it pins only half of law 4")
	}
}

// Law 5: d =D e implies the same recognizer outcome, and equal outputs on success.
// Needs two NODES; the corpus `note` claimed this for a single vector until ontos-internal#286.
func TestDEqualNodesPinLaw5(t *testing.T) {
	vf := load(t)
	for _, c := range vf.DEqualNodes {
		c := c
		t.Run(c.Name, func(t *testing.T) {
			left := parseNode(t, c.Left)
			right := parseNode(t, c.Right)
			if !nodesEqual(left, right) {
				t.Fatalf("the corpus claim about =D is wrong: these nodes are not deixis-equal")
			}
			a, errA := projection.Recognize(left)
			b, errB := projection.Recognize(right)
			if (errA == nil) != (errB == nil) {
				t.Fatalf("law 5: equal nodes reached different outcomes (%v vs %v)", errA, errB)
			}
			if errA == nil && !core.Equal(a, b) {
				t.Error("law 5: equal nodes recognized to different values")
			}
		})
	}
}

// Equality is over the WHOLE Option payload. These pairs must stay apart, and each names
// a way a lax relation would merge them.
func TestDDistinctNodesPinPayloadEquality(t *testing.T) {
	vf := load(t)
	if len(vf.DDistinctNodes) == 0 {
		t.Fatal("d_distinct_nodes section is empty — vector file shrank?")
	}
	for _, c := range vf.DDistinctNodes {
		c := c
		t.Run(c.Name, func(t *testing.T) {
			left := parseNode(t, c.Left)
			right := parseNode(t, c.Right)
			if nodesEqual(left, right) {
				t.Fatalf("=D merged two distinct nodes: %s", c.Reason)
			}
			// Reflexivity, so a relation that merely answers false cannot pass.
			if !nodesEqual(left, left) || !nodesEqual(right, right) {
				t.Fatal("=D is not reflexive")
			}
		})
	}
}

// walkValue follows an ontos index path. ok=false means it does not resolve.
func walkValue(v core.Value, path []int) (core.Value, bool) {
	cur := v
	for _, i := range path {
		t, isTuple := cur.(core.Tuple)
		if !isTuple || i < 0 || i >= t.Len() {
			return nil, false
		}
		cur = t.At(i)
	}
	return cur, true
}

// walkNode follows the corresponding deixis key path (κ(i₀), …, κ(iₖ)). It compares keys
// octet-wise and never parses one, exactly as R does.
func walkNode(n projection.Node, path []int) (projection.Node, bool) {
	cur := n
	for _, i := range path {
		want := pos.Key(uint64(i))
		found := false
		for _, e := range cur.Entries() {
			if bytes.Equal(e.Key, want) {
				cur, found = e.Node, true
				break
			}
		}
		if !found {
			return cur, false
		}
	}
	return cur, true
}

// Law 7: the index path resolves in v IFF the key path resolves in P(v), and on success it
// reaches P of the SAME subvalue. Both halves matter -- a face could agree on reachability
// everywhere and still land on the wrong node.
func TestPathsPinLaw7(t *testing.T) {
	vf := load(t)
	sawResolving, sawAbsent := false, false
	for _, c := range vf.Paths {
		c := c
		t.Run(c.Name, func(t *testing.T) {
			value := parseValue(t, c.Value)
			if c.Resolves {
				sawResolving = true
			} else {
				sawAbsent = true
			}

			byIndex, indexOK := walkValue(value, c.IndexPath)
			if indexOK != c.Resolves {
				t.Fatalf("the corpus claim about the INDEX path is wrong: resolves=%v, want %v", indexOK, c.Resolves)
			}

			node := projection.Project(value)
			byKeys, keysOK := walkNode(node, c.IndexPath)
			if keysOK != c.Resolves {
				t.Errorf("law 7: the two paths disagree about reachability (index=%v, keys=%v)", indexOK, keysOK)
			}

			if c.Resolves {
				sub := parseValue(t, c.Subvalue)
				if !core.Equal(byIndex, sub) {
					t.Fatalf("the corpus claim about the SUBVALUE is wrong")
				}
				if !nodesEqual(byKeys, projection.Project(sub)) {
					t.Error("law 7: the key path reaches a node that is not P(subvalue)")
				}
			}
		})
	}
	// Both directions of the iff, or the section pins half a law.
	if !sawResolving || !sawAbsent {
		t.Fatal("paths must carry resolving AND non-resolving cases")
	}
}
